// CATALOGUE — TROIS NIVEAUX
// -------------------------
// FAMILLE  →  GAMME  →  PRODUIT
// Fichier produit par l'atelier : 

export const FAMILLES = [
  {
    id: "video-cellule",
    nom: "VIDEO CELLULE ",
    emoji: "🎬",
    glyphe: "etoile",
    image: "/produits/video-cellule.jpg",
    type: "videos",
    couleurs: ["#00E5FF", "#7B2FF7"],
    gammes: [
      {
        id: "cellule-mapuche",
        nom: "CELLULE MAPUCHE",
        etiquette: "",
        sousTitre: "",
        produits: [
          { ref: "VID-001", nom: "Collection 1", unite: "", prix: 0, dispo: true, image: "/produits/sans-nom.jpg", video: "/videos/cellue-mapuche-2.mp4" },
          { ref: "REF-002", nom: "Collection 2", unite: "la pièce", prix: 0, dispo: true, image: "/produits/28.jpg", video: "/videos/mapuche-2.mp4" },
        ],
      },
      {
        id: "cellule-ville-franche",
        nom: "CELLULE VILLE-FRANCHE",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "Ville-Franche 1", unite: "la pièce", prix: 0, dispo: true, image: "/produits/nouveau-produit-2.jpg", video: "/videos/ville-franche1.mp4" },
          { ref: "REF-002", nom: "Ville-Franche 2", unite: "la pièce", prix: 0, dispo: true, image: "/produits/30.jpg", video: "/videos/ville-franche2.mp4" },
        ],
      },
      {
        id: "cellule-roche-sur-lyon",
        nom: "CELLULE ROCHE SUR LYON",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "", unite: "la pièce", prix: 0, dispo: true, image: "/produits/hjk.jpg", video: "/videos/roche-sur-lyon.mp4" },
        ],
      },
      {
        id: "cellule-roanne",
        nom: "CELLULE ROANNE",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "", unite: "la pièce", prix: 0, dispo: true, image: "/produits/26.jpg", video: "/videos/roanne.mp4" },
        ],
      },
      {
        id: "cellule-saint-etienne",
        nom: "CELLULE SAINT-ETIENNE ",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "", unite: "la pièce", prix: 0, dispo: true, image: "/produits/saint.jpg", video: "/videos/saint-etienne.mp4" },
        ],
      },
      {
        id: "cellule-bourg-en-bresse",
        nom: "CELLULE BOURG-EN-BRESSE",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "", unite: "la pièce", prix: 0, dispo: true, image: "/produits/bourg.jpg", video: "/videos/bourg-en-bresse.mp4" },
        ],
      },
    ],
  },
  {
    id: "drapeaux",
    nom: "DRAPEAUX ",
    emoji: "🔫",
    glyphe: "boite",
    image: "/produits/drapeaux.jpg",
    type: "produits",
    couleurs: ["#7B2FF7", "#FF1B8D"],
    gammes: [
      {
        id: "collection-omerta",
        nom: "Collection OMERTA",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "Vatos Locos", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/vatos-locos.jpg" },
          { ref: "REF-002", nom: "Dollars Goku", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", cadragePos: "36% 52%", image: "/produits/dollars-goku.jpg" },
          { ref: "REF-003", nom: "Dollars Zoro", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/dollars-zoro.jpg" },
          { ref: "REF-004", nom: "Omerta Goku", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/omerta-goku.jpg" },
          { ref: "REF-005", nom: "Fuck Goku", unite: "la pièce", prix: 20, dispo: true, chef: true, vedette: true, cadrage: "entier", image: "/produits/fuck-goku.jpg" },
          { ref: "REF-006", nom: "Dollars Luffy", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/dollars-luffy.jpg" },
          { ref: "REF-007", nom: "Fuck Vegeta", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/fuck-vegeta.jpg" },
          { ref: "REF-008", nom: "Dollars Vegeta", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/dollars-vegeta.jpg" },
          { ref: "REF-009", nom: "Fuck Luffy", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/fuck-luffy.jpg" },
          { ref: "REF-010", nom: "Fuck Zoro ", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/fuck-zoro.jpg" },
          { ref: "REF-011", nom: "Omerta Vegeta", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/omerta-vegeta.jpg" },
        ],
      },
      {
        id: "collection-gta",
        nom: "Collection GTA",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: " GTA Marseille ", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-marseille.jpg" },
          { ref: "REF-002", nom: "GTA Grenoble", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-grenoble.jpg" },
          { ref: "REF-003", nom: "GTA Lyon", unite: "la pièce", prix: 20, dispo: true, chef: true, image: "/produits/gta-lyon.jpg" },
          { ref: "REF-004", nom: "GTA Paris ", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-paris.jpg" },
          { ref: "REF-005", nom: "GTA Colombie ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/gta-colombie.jpg" },
          { ref: "REF-006", nom: "GTA Maroco ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/gta-maroco.jpg" },
          { ref: "REF-007", nom: "GTA DBZ", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-dbz.jpg" },
          { ref: "REF-008", nom: "GTA One Piece", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-one-piece.jpg" },
          { ref: "REF-009", nom: "GTA Akatsuki", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/gta-akatsuki.jpg" },
        ],
      },
      {
        id: "collection-mma-1",
        nom: "Collection MMA 1 ",
        etiquette: "FR",
        sousTitre: "Tous les produits Collection 1 MMA",
        produits: [
          { ref: "REF-001", nom: "MMA1 Goku ", unite: "la pièce", prix: 10, dispo: true, cadrage: "entier", image: "/produits/mma1-goku.jpg" },
          { ref: "REF-002", nom: "MMA1 Broly ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-broly.jpg" },
          { ref: "REF-003", nom: "MMA1 Gohan ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-gohan.jpg" },
          { ref: "REF-004", nom: "MMA1 Cell ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-cell.jpg" },
          { ref: "REF-005", nom: "MMA1 Doflamingo ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-doflamingo.jpg" },
          { ref: "REF-006", nom: "MMA1 Luffy ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-luffy.jpg" },
          { ref: "REF-007", nom: "MMA1 Naruto ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-naruto.jpg" },
          { ref: "REF-008", nom: "MMA1 Sasuke", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-sasuke.jpg" },
          { ref: "REF-009", nom: "MMA1 Mihawk", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-mihawk.jpg" },
          { ref: "REF-010", nom: "MMA1 Buu", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-buu.jpg" },
          { ref: "REF-011", nom: "MMA1 Trunks", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-trunks.jpg" },
          { ref: "REF-012", nom: "MMA1 Vegeta", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-vegeta.jpg" },
          { ref: "REF-013", nom: "MMA1 Zoro ", unite: "la pièce", prix: 0, dispo: true, image: "/produits/mma1-zoro.jpg" },
          { ref: "REF-014", nom: "MMA1 Sanji", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-sanji.jpg" },
          { ref: "REF-015", nom: "MMA1 Ace", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mma1-ace.jpg" },
        ],
      },
      {
        id: "collection-mma-2",
        nom: "Collection MMA 2",
        etiquette: "FR",
        sousTitre: "Tous les produits Collection 2 MMA",
        produits: [
          { ref: "REF-001", nom: "MMA2 Black Freezer Vrunk", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/mma2-black-freezer-vrunk.jpg" },
          { ref: "REF-002", nom: "MMA2 Black Goku 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-black-goku-2.jpg" },
          { ref: "REF-003", nom: "MMA2 Black Goku", unite: "la pièce", prix: 20, dispo: false, image: "/produits/mma2-black-goku.jpg" },
          { ref: "REF-004", nom: "MMA2 Broly 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-broly-2.jpg" },
          { ref: "REF-005", nom: "MMA2 Broly 3", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-broly-3.jpg" },
          { ref: "REF-006", nom: "MMA2 Broly SSJ1 Vrunk", unite: "la pièce", prix: 20, dispo: true, chef: true, vedette: true, image: "/produits/mma2-broly-ssj1-vrunk.jpg" },
          { ref: "REF-007", nom: "MMA2 Buu Vrunk", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-buu-vrunk.jpg" },
          { ref: "REF-008", nom: "MMA2 Buu 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-buu-2.jpg" },
          { ref: "REF-009", nom: "MMA2 Cell 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-cell-2.jpg" },
          { ref: "REF-010", nom: "MMA2 Gohan 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-gohan-2.jpg" },
          { ref: "REF-011", nom: "MMA2 Goku Maroc", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-goku-maroc.jpg" },
          { ref: "REF-012", nom: "MMA2 Goku SSJ 3 ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-goku-ssj-3.jpg" },
          { ref: "REF-013", nom: "MMA2 Goku Vs Vegeta", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-goku-vs-vegeta.jpg" },
          { ref: "REF-014", nom: "MMA2 Luffy 2", unite: "la pièce", prix: 20, dispo: false, image: "/produits/mma2-luffy-2.jpg" },
          { ref: "REF-015", nom: "MMA2 Majin Vegeta ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-majin-vegeta.jpg" },
          { ref: "REF-016", nom: "MMA2 Vegetta M Bleu", unite: "la pièce", prix: 20, dispo: false, image: "/produits/mma2-vegetta-m-bleu.jpg" },
          { ref: "REF-017", nom: "MMA2 Vegeta DZ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-vegeta-dz.jpg" },
          { ref: "REF-018", nom: "MMA2 Vegeta Ultra Ego Vrunk", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-vegeta-ultra-ego-vrunk.jpg" },
          { ref: "REF-019", nom: "MMA2 Zoro 2", unite: "la pièce", prix: 20, dispo: true, image: "/produits/mma2-zoro-2.jpg" },
        ],
      },
      {
        id: "collection-felins",
        nom: "Collection FÉLINS",
        etiquette: "FR",
        sousTitre: "Lion blanc, tigre blanc, jaguar",
        produits: [
          { ref: "MA-DR-FEL", nom: "Drapeaux Félins", unite: "la pièce", prix: 20, dispo: true, chef: true, image: "/produits/drapeaux-felins-2.jpg", 
            images: ["/produits/drapeaux-felins-2.jpg", "/produits/drapeaux-felins.jpg"] },
          { ref: "MA-DR-FELB", nom: "Drapeaux Félins Bébé", unite: "la pièce", prix: 20, dispo: true, image: "/produits/drapeaux-felins-bebe-2.jpg", 
            images: ["/produits/drapeaux-felins-bebe-2.jpg", "/produits/drapeaux-felins-bebe.jpg"] },
        ],
      },
      {
        id: "collection-drapeaux-nationaux",
        nom: "Collection DRAPEAUX NATIONAUX",
        etiquette: "FR",
        sousTitre: "Emblèmes et animaux",
        produits: [
          { ref: "MA-DR-MAR", nom: "Drapeau Maroc — Lion de l'Atlas", unite: "la pièce", prix: 20, dispo: true, chef: true, image: "/produits/drapeau-maroc-lion-de-l-atlas.jpg", 
            images: ["/produits/drapeau-maroc-lion-de-l-atlas.jpg", "/produits/drapeau-maroc.jpg"] },
          { ref: "MA-DR-ALG", nom: "Drapeau Algérie — Fennec", unite: "la pièce", prix: 20, dispo: false, image: "/produits/drapeau-algerie-fennec.jpg", 
            images: ["/produits/drapeau-algerie-fennec.jpg", "/produits/drapeau-algerie.jpg"] },
        ],
      },
      {
        id: "collection-voiture",
        nom: "COLLECTION VOITURE",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "Audi R8", unite: "la pièce", prix: 10, dispo: true, image: "/produits/audi-r8.jpg" },
          { ref: "REF-002", nom: "Audi RS Q3", unite: "la pièce", prix: 10, dispo: true, image: "/produits/audi-rs-q3.jpg" },
          { ref: "REF-003", nom: "Audi RS4", unite: "la pièce", prix: 10, dispo: false, image: "/produits/audi-rs4.jpg" },
          { ref: "REF-004", nom: "Audi RS5", unite: "la pièce", prix: 10, dispo: false, image: "/produits/audi-rs5.jpg" },
          { ref: "REF-005", nom: "Audi RS6", unite: "la pièce", prix: 0, dispo: false, image: "/produits/audi-rs6.jpg" },
          { ref: "REF-006", nom: "BMW M3", unite: "la pièce", prix: 10, dispo: false, image: "/produits/bmw-m3.jpg" },
          { ref: "REF-007", nom: "BMW M5", unite: "la pièce", prix: 10, dispo: false, image: "/produits/bmw-m5.jpg" },
          { ref: "REF-008", nom: "BMW M8", unite: "la pièce", prix: 10, dispo: false, image: "/produits/bmw-m8.jpg" },
          { ref: "REF-009", nom: "BMW X6", unite: "la pièce", prix: 10, dispo: false, image: "/produits/bmw-x6.jpg" },
          { ref: "REF-011", nom: "BMW M4", unite: "la pièce", prix: 10, dispo: true, image: "/produits/bmw-m4.jpg" },
          { ref: "REF-013", nom: "Mercedes AMG GTS", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mercedes-amg-gts.jpg" },
          { ref: "REF-014", nom: "Mercedes AMG GT", unite: "la pièce", prix: 10, dispo: false, image: "/produits/mercedes-amg-gt.jpg" },
          { ref: "REF-015", nom: "Mercedes C63 jaune", unite: "la pièce", prix: 0, dispo: false, image: "/produits/mercedes-c63.jpg" },
          { ref: "REF-016", nom: "Mercedes C63 Rouge ", unite: "la pièce", prix: 0, dispo: true, image: "/produits/mercedes-c63-rouge.jpg" },
          { ref: "REF-017", nom: "Mercedes G36", unite: "la pièce", prix: 10, dispo: false, image: "/produits/mercedes-g36.jpg" },
          { ref: "REF-018", nom: "Mercedes GLE", unite: "la pièce", prix: 10, dispo: true, image: "/produits/mercedes-gle.jpg" },
          { ref: "REF-019", nom: "Audi RS3 Gris Bleu ", unite: "la pièce", prix: 10, dispo: true, image: "/produits/audi-rs3-gris-bleu.jpg" },
          { ref: "REF-020", nom: "Audi RS4 Gris", unite: "la pièce", prix: 20.01, dispo: true, image: "/produits/audi-rs4-gris.jpg" },
          { ref: "REF-021", nom: "Audi RS6 GT", unite: "la pièce", prix: 20, dispo: true, image: "/produits/audi-rs6-gt.jpg" },
          { ref: "REF-020", nom: "BMW-M3 E43 GTR", unite: "la pièce", prix: 20, dispo: true, image: "/produits/bmw-m3-e43-gtr.jpg" },
          { ref: "REF-021", nom: "BMW-M5 Bleu Noire", unite: "la pièce", prix: 0, dispo: true, image: "/produits/bmw-m5-bleu-noire.jpg" },
        ],
      },
      {
        id: "collection-moto-dbz",
        nom: "Collection Moto DBZ",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "Goku KTM", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/goku-ktm.jpg" },
          { ref: "REF-002", nom: "Zoro KX", unite: "la pièce", prix: 20, dispo: true, cadrage: "entier", image: "/produits/zoro-kx.jpg" },
          { ref: "REF-003", nom: "Vegeta YZ", unite: "la pièce", prix: 20, dispo: true, image: "/produits/vegeta-yz.jpg" },
          { ref: "REF-004", nom: "Lufy CR", unite: "la pièce", prix: 20, dispo: true, image: "/produits/lufy-cr.jpg" },
        ],
      },
    ],
  },
  {
    id: "serviettes-de-plage",
    nom: "SERVIETTES DE PLAGE",
    emoji: "🏖️",
    glyphe: "serviette",
    image: "/produits/serviettes-de-plage.jpg",
    type: "produits",
    couleurs: ["#F7C873", "#B8791A"],
    gammes: [
      {
        id: "collection-gta",
        nom: "COLLECTION GTA",
        etiquette: "FR",
        sousTitre: "Microfibre",
        produits: [
          { ref: "REF-001", nom: "Serviette GTA Paris", unite: "la pièce", prix: 30, dispo: true, image: "/produits/serviette-gta-paris.jpg", video: "/videos/serviette-gta-paris.mp4" },
          { ref: "REF-002", nom: "Serviette GTA Lyon", unite: "la pièce", prix: 30, dispo: true, vedette: true, image: "/produits/serviette-gta-lyon.jpg", video: "/videos/serviette-gta-lyon.mp4" },
          { ref: "REF-003", nom: "Serviette GTA Colombia", unite: "la pièce", prix: 30, dispo: true, image: "/produits/serviette-gta-colombia.jpg", video: "/videos/serviette-gta-colombia.mp4" },
          { ref: "REF-004", nom: "Serviette GTA DBZ", unite: "la pièce", prix: 30, dispo: true, image: "/produits/serviette-gta-dbz.jpg", video: "/videos/serviette-gta-dbz.mp4" },
          { ref: "REF-005", nom: "Serviette GTA One Piece", unite: "la pièce", prix: 30, dispo: true, image: "/produits/serviette-gta-one-piece.jpg", video: "/videos/serviette-gta-one-piece.mp4" },
        ],
      },
      {
        id: "collection-real-street",
        nom: "COLLECTION REAL STREET",
        etiquette: "FR",
        sousTitre: "Microfibre",
        produits: [
          { ref: "MA-SV-COL", nom: "Serviette Colombia", unite: "la pièce", prix: 30, dispo: false, image: "/produits/serviette-colombia.jpg" },
          { ref: "MA-SV-BIKE", nom: "Serviette BikeLife", unite: "la pièce", prix: 30, dispo: false, image: "/produits/serviette-bikelife.jpg" },
          { ref: "MA-SV-MONEY", nom: "Serviette Street Money", unite: "la pièce", prix: 30, dispo: false, image: "/produits/serviette-street-money.jpg" },
        ],
      },
    ],
  },
  {
    id: "housses-de-couette",
    nom: "HOUSSES DE COUETTE",
    emoji: "🛏️",
    glyphe: "housse",
    image: "/produits/housses-de-couette.jpg",
    type: "produits",
    couleurs: ["#7A1420", "#FB3640"],
    gammes: [
      {
        id: "blasons-trois-singes",
        nom: "BLASONS & TROIS SINGES",
        etiquette: "FR",
        sousTitre: "1 personne",
        produits: [
          { ref: "MA-HC-FRA", nom: "Housse France — Blason & Trois Singes", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-france.jpg" },
          { ref: "MA-HC-ESP", nom: "Housse Espagne — Blason Royal", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-espagne.jpg" },
          { ref: "MA-HC-ITA", nom: "Housse Italie — Blason & Omerta", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-italie.jpg" },
        ],
      },
      {
        id: "collection-street",
        nom: "COLLECTION STREET",
        etiquette: "FR",
        sousTitre: "1 personne",
        produits: [
          { ref: "MA-HC-COL", nom: "Housse Colombia", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-colombia.jpg" },
          { ref: "MA-HC-MONEY", nom: "Housse Street Money", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-street-money.jpg" },
          { ref: "MA-HC-BIKE", nom: "Housse BikeLife", unite: "la pièce", prix: 40, dispo: false, image: "/produits/housse-bikelife.jpg" },
        ],
      },
    ],
  },
  {
    id: "produit-electro",
    nom: "PRODUIT ÉLECTRO ",
    emoji: "🔌",
    glyphe: "boite",
    image: "/produits/produit-electro.jpg",
    type: "produits",
    couleurs: ["#FF1B8D", "#7B2FF7"],
    gammes: [
      {
        id: "dyson",
        nom: "DYSON",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "Dyson Airstrait", unite: "la pièce", prix: 170, dispo: true, vedette: true, image: "/produits/dyson-airstrait.jpg", 
            images: ["/produits/dyson-airstrait.jpg", "/produits/dyson-airstrait-2.jpg", "/produits/dyson-airstrait-3.jpg"], 
            description: "Quelle est sa fonction principale ?\nContrairement à un lisseur traditionnel qui utilise des plaques chauffantes en céramique ou en titane pour écraser et lisser le cheveu, cette machine utilise uniquement un flux d'air à haute pression.\nSon but est de sécher les cheveux mouillés tout en les lissant simultanément, le tout sans utiliser de chaleur extrême." },
          { ref: "REF-002", nom: "Dyson Airwrap", unite: "la pièce", prix: 200, dispo: true, image: "/produits/dyson-airwrap.jpg", 
            images: ["/produits/dyson-airwrap.jpg", "/produits/dyson-airwrap-2.jpg", "/produits/dyson-airwrap-3.jpg"], 
            description: "Quelle est sa fonction principale ?\nCet appareil est un véritable \"couteau suisse\" de la coiffure. Sa fonction est de permettre de réaliser tous les types de coiffures (séchage, lissage, ondulations, boucles, volume) avec un seul et même appareil, en changeant simplement la tête au bout du manche. Le tout, toujours sur cheveux humides et sans chaleur extrême." },
        ],
      },
      {
        id: "apple-airpods-max-2",
        nom: "Apple AirPods Max 2",
        etiquette: "FR",
        sousTitre: "",
        produits: [
          { ref: "REF-001", nom: "AirPods Max 2", unite: "la pièce", prix: 120, dispo: true, image: "/produits/airpods-max-2.jpg", 
            images: ["/produits/airpods-max-2.jpg", "/produits/airpods-max-2-2.jpg", "/produits/airpods-max-2-3.jpg"], 
            description: "Quelle est sa fonction principale ?\nLa fonction de cet appareil est d'offrir ce que l'image décrit comme \"L'expérience d'écoute personnelle à son apogée\". Il sert à écouter de la musique, regarder des films ou passer des appels avec une qualité sonore de très haute fidélité, tout en permettant à l'utilisateur de s'isoler totalement des bruits de son environnement grâce à des technologies d'annulation du son." },
        ],
      },
    ],
  },
  {
    id: "vetements-chaussures",
    nom: "VÊTEMENTS/CHAUSSURES ",
    emoji: "👟",
    glyphe: "boite",
    image: "",
    type: "produits",
    couleurs: ["#FF1B8D", "#7B2FF7"],
    gammes: [

    ],
  },
];

// Raccourcis pratiques, calculés une fois au démarrage.
export const TOUS_PRODUITS = FAMILLES.flatMap((f) =>
  f.gammes.flatMap((g) => g.produits.map((p) => ({ ...p, famille: f, gamme: g })))
);

export const SELECTION_CHEF = TOUS_PRODUITS.filter((p) => p.chef);
