// VERSION DU MOTEUR
// -----------------
// Ce fichier ne contient rien de propre à la boutique : il dit seulement quelle
// version du moteur elle fait tourner. La boutique le publie dans donnees.json,
// et l'atelier compare cette version à la sienne pour savoir si une mise à jour
// existe.
//
// Ne pas modifier à la main. La version est celle du logiciel qui a créé ou mis
// à jour cette boutique.

export const MOTEUR = {
  modele: "vitrine-3-niveaux",
  version: "3.41",
  // Ce que sait faire cette version, pour information.
  capacites: [
    "familles > gammes > produits",
    "panier et commande WhatsApp",
    "plusieurs photos par produit avec visionneuse",
    "video par produit",
    "famille galerie de videos",
    "ouverture animee au demarrage",
    "image de fond et espaces transparents",
    "photo entiere ou recadree, au choix",
    "un produit en vedette sur l accueil",
    "commande sur WhatsApp, Telegram, Signal ou Snapchat",
    "photos en portrait, paysage ou forme d origine",
    "photos enregistrees entieres, cadrage modifiable a tout moment",
    "presentation en familles ou en liste, au choix",
    "les deux types de boutique sont separes : corriger l un ne touche pas l autre",
    "choisir une categorie ne montre plus que cette categorie",
    "une famille sans article le dit, au lieu d ouvrir un ecran vide",
    "trois types de boutique : par familles, en liste, ou La Maison",
    "une famille mene directement a ses articles, avec un bouton pour remonter",
    "des references de produit en double n empechent plus l affichage",
    "un bouton ouvre la liste complete des familles, rien n est cache hors de l ecran",
    "moyens de paiement annonces, avec liens vers le prestataire",
    "le montant du panier est ajoute au lien PayPal",
    "moyens de paiement sur mesure, nom et lien au choix du vendeur",
    "un moyen de paiement sans compte relie n est jamais propose au client",
    "compte prive ou pro, paiement entre proches ou biens et services, au choix",
    "reference de commande, pour rapprocher un virement d une commande",
    "le bouton d envoi dans la conversation peut etre eteint",
    "sans contact ni paiement, la boutique devient une vitrine sans panier",
    "des avis en images : les captures de conversations defilent en carrousel",
    "le client ne depose plus d avis lui-meme : le vendeur seul les publie",
    "sans moyen d etre contacte, aucun lien vers la messagerie nulle part",
    "quatre types de boutique : familles, liste, La Maison, ou par marques",
    "type par marques : une grande photo par marque, puis un carrousel page a page",
    "taille et couleur sur la fiche produit, affichees seulement si renseignees",
    "la taille et la couleur se choisissent au doigt et partent avec la commande",
    "les pointures en rupture sont barrees, visibles mais pas commandables",
    "les photos de marque prennent la meme forme que les photos de produit",
    "une marque peut avoir une video qui tourne a la place de sa photo",
    "chaque marque occupe tout l ecran du telephone, une marque a la fois",
    "les modeles d une marque en vignettes : on voit les couleurs et on choisit",
    "les tailles se lisent quelle que soit la facon de les ecrire : points, virgules, espaces",
    "type par marques : photo en haut, tailles et prix dessous, dans une colonne",
    "la video d un produit se joue a meme la fiche, a la place de la photo",
    "une famille entiere peut passer en rupture, sans etre supprimee",
    "promotions -25 ou -50 pour cent, par produit, par gamme ou par famille entiere",
    "le prix de depart reste affiche, barre, a cote du prix promotionnel",
    "le panier dit quoi donner pour etre livre, et sous quel delai la commande part",
    "les lignes nom, adresse et telephone partent avec la commande, a completer",
    "une promotion peut avoir un dernier jour : la boutique reprend ses prix normaux toute seule",
    "un rayon TOUTES LES PROMOTIONS apparait tout seul les jours de promotion",
    "la pastille -50 % se voit des l accueil, sur les vedettes",
    "en presentation liste, une pastille 44 EN PROMOTION filtre les articles remises",
    "un article epuise ne figure pas dans les promotions : on n y promet rien qu on ne peut vendre",
    "un article epuise ne porte aucune remise, meme dans son rayon : il garde son prix normal",
    "les ecrans glissent : un rayon entre par la droite, un retour repart vers la gauche",
    "les cartes apparaissent l une apres l autre, le rayon se remplit au lieu de clignoter",
    "frais d envoi annonces dans le panier, offerts au-dela d un montant d achat",
    "le montant envoye au prestataire comprend les frais d envoi",
    "la photo de l article s affiche dans le panier, avec sa taille et sa couleur",
    "le montant et la reference se copient d un doigt, pour les payer qui ne les pre-remplissent pas",
  ],
};
